services:
  app:
    build: .
    ports:
      - "10202:8000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=planty
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=planty
    volumes:
      - mysql_data:/var/lib/mysql

  wireguard:
    image: linuxserver/wireguard
    restart: unless-stopped
    volumes:
      - './config:/config'
      - '/lib/modules:/lib/modules:ro'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "10210:80"

  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: service:wireguard
    depends_on:
      - wireguard
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  tcp_proxy_9090:
    image: alpine/socat
    restart: unless-stopped
    network_mode: service:wireguard
    depends_on:
      - wireguard
    command: tcp-listen:9090,fork,reuseaddr tcp-connect:10.8.0.16:9090

volumes:
  mysql_data:
